カップ麺の商品情報の追加
takuma-ru/CupMENWeb pull request #7
Opened 2020-12-28 08:24 UTC by takuma-ru

カップ麺の商品情報の追加
追加したものは以下の通り

- サンヨー食品
- 明星食品
- ご当地カップ麺

2021-01-10 00:43 UTC, SuzuSys requested changes
`"description": "「愛をとりもつ」"`を改善すれば問題ないです

2021-01-10 02:05 UTC, takuma-ru commented
修正しました。
どうでしょう？

2021-01-10 15:25 UTC, SuzuSys approved these changes
LGTM.

2021-01-12 02:47 UTC, aoi-aoao approved these changes
LGTM

2021-01-12 03:31 UTC, merged